### ISSUE TITLE
Routes for "Get banks by bank name" is not working.

### ISSUE THREAD

**Issue by barodiamansi** [mangrep/ifsc-rest-api#5]
I am using this API in my app and I noticed that the route mentioned on the readme for "Get banks by bank name" is not working. This is the route - http://api.techm.co.in/api/bank/ABU%20DHABI%20COMMERCIAL%20BANK 

Error:
{"status":"failed","message":"Invalid route"}

I even tried with different bank names and getting the same error.

**Comment by mangrep** [comment]
Hi Mansi,

Thanks for reaching out. 

I have disabled the api in order to improve performance/turnaround time . As this api sends big chunk of data, it affects normal users. If you need this api I will request you to fork the project and host it on your server. I will provide complete JSON list of banks.

To get the bank JSON list please drop me a mail.

**Comment by barodiamansi** [comment]
Hello Manish,

Yes I understand performance is more important over functionality. I will use alternative API's from your list to get what I need. 

Thanks!
